### ISSUE TITLE
Wrong command usage error when using /openmod install command

### ISSUE THREAD

**Issue by iamsilk** [openmod/openmod#574] opened 2021-09-07 18:58 UTC
Unsure of steps to reproduce, or what's causing the error, but multiple reports have been given in the Discord of a wrong command usage error occurring when running the command `/openmod install OpenMod.EntityFrameworkCore.MySql`. This may be the case with other package IDs as well.

**Comment by RoBoT245** [comment] 2023-06-02 01:20
Anyone ever find the fix for this?

**Comment by CyberAndrii** [comment] 2023-06-14 11:54
This issue occurs when there is an extra space at the end. Only in Unturned, works fine on standalone.

![image](https://github.com/openmod/openmod/assets/37713088/da0473d4-5d8b-404e-ae18-6243b0721e3a)

**Comment by DevInc0** [comment] 2023-09-21 19:29
Looks like `ArgumentsParser` returns extra empty argument if there's a whitespace in the end of a line.

![image](https://github.com/openmod/openmod/assets/63493877/8f9f97af-6ca3-423f-80c5-66cc9d743cb7)

And then in `OnExecuteAsync()` of `CommandOpenModInstall` it checks for `string.IsNullOrWhiteSpace()` and throws an exception.

https://github.com/openmod/openmod/blob/405973f72786bac7ec80868729a7f937820b9294/framework/OpenMod.Core/Commands/OpenModCommands/CommandOpenModInstall.cs#L57-L60

So it's more the problem of `ArgumentsParser`, than `/openmod install` command.

If we fix `ArgumentsParser` bug, then it'll fix potential bugs in other commands.

**Comment by DevInc0** [comment] 2023-09-21 20:05
I think the problem is that `ArgumentsParser` does not check last argument for being an empty string.

https://github.com/openmod/openmod/blob/405973f72786bac7ec80868729a7f937820b9294/framework/OpenMod.Core/Helpers/ArgumentsParser.cs#L85-L88

And if we rewrite it into this:

```cs
var currentArgAsString = currentArg.ToString();

if (!string.IsNullOrEmpty(currentArgAsString))
    args.Add(currentArgAsString);

return args.ToArray();
```

Then the output will be normal even with several white spaces:

![image](https://github.com/openmod/openmod/assets/63493877/b28e76a4-4173-4ea9-827c-bfe2868c7752)

**Comment by rube200** [comment] 2023-09-21 20:09
Is it a space or black string?

**Comment by DevInc0** [comment] 2023-09-21 20:21
Blank string, like string.Empty

**Comment by rube200** [comment] 2023-09-21 20:24
Don't check for empty
use currentArg.Length != 0 instead
same as above (on switch statement)

**Closed** 2023-09-22 06:40 UTC
Labels: bug, help wanted, area-Framework
