### ISSUE TITLE
Shutting down Exception

### ISSUE THREAD

**Issue by HanaForward** [openmod/openmod#264] opened 2020-11-26 08:59 UTC
[OpenMod.Core.Console.ConsoleActor] Shutting down...
CWorkThreadPool::~CWorkThreadPool: work complete queue not empty, 1 items discarded.
[OpenMod.Runtime.Runtime] OpenMod is shutting down...
Microsoft.Extensions.Hosting.Internal.ApplicationLifetime] An error occurred stopping the application
System.AggregateException: One or more errors occurred. ---> System.Exception: Tried to save null users data

**Comment by HanaForward** [comment] 2020-11-26 09:00
[OpenMod.Runtime.OpenModHostedService] Loading plugins...
OpenMod.Runtime.OpenModHostedServiceUnloading 4 Unused Serialized files (Serialized files now loaded: 0)
] > 0 plugins loaded.

I dont has any plugin

**Comment by Trojaner** [comment] 2020-11-26 09:23
Duplicate of #262 will be fixed in next version

**Closed by Trojaner** 2020-11-26 09:23 UTC
