### ISSUE TITLE
Shutdown Error

### ISSUE THREAD

**Issue by nazmiyigitefe** [openmod/openmod#267] opened 2020-11-28 18:41 UTC
When I Use Shutdown In My Server I'm Taking That Error.

Informations;

OS : Windows Server 2012 R2
OpenMod Version : 2.3.8
Unturned Version : 3.20.15.2

Files;

Image : I Can't Upload A File Cuz The Error Is Soo Long.
Log File :  [https://mega.nz/file/zmxnHK7J#8f4C9k6bOPiddqTP9pzl8GHJu7n9-EZ4ZDrkMpL3C1I](url) | VirusTotal : [https://www.virustotal.com/gui/file/de1e7ba6d8ba33e96e1489209494ed80447dacf2ca77388c5eb7924f03aeeea3/detection](url)

**Comment by Trojaner** [comment] 2020-11-28 19:01
Duplicate of #262 #264

>

**Closed by Trojaner** 2020-11-28 19:01 UTC
